### ISSUE TITLE
clean install no loader specified

### ISSUE THREAD

**Issue by timvink** [timvink/mkdocs-git-revision-date-localized-plugin#1]
@squidfunk reported in https://github.com/squidfunk/mkdocs-material/pull/1373 the following error

```
INFO    -  Building documentation... 
INFO    -  Cleaning site directory 
ERROR   -  Error reading page 'customization.md': no loader for this environment specified 
Traceback (most recent call last):
  File "./venv/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/Users/squidfunk/Desktop/General/Sources/mkdocs-material/venv/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/squidfunk/Desktop/General/Sources/mkdocs-material/venv/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/squidfunk/Desktop/General/Sources/mkdocs-material/venv/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/squidfunk/Desktop/General/Sources/mkdocs-material/venv/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/squidfunk/Desktop/General/Sources/mkdocs-material/venv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/squidfunk/Desktop/General/Sources/mkdocs-material/venv/lib/python3.7/site-packages/mkdocs/__main__.py", line 134, in serve_command
    livereload=livereload
  File "/Users/squidfunk/Desktop/General/Sources/mkdocs-material/venv/lib/python3.7/site-packages/mkdocs/commands/serve.py", line 119, in serve
    config = builder()
  File "/Users/squidfunk/Desktop/General/Sources/mkdocs-material/venv/lib/python3.7/site-packages/mkdocs/commands/serve.py", line 114, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "/Users/squidfunk/Desktop/General/Sources/mkdocs-material/venv/lib/python3.7/site-packages/mkdocs/commands/build.py", line 274, in build
    _populate_page(file.page, config, files, dirty)
  File "/Users/squidfunk/Desktop/General/Sources/mkdocs-material/venv/lib/python3.7/site-packages/mkdocs/commands/build.py", line 174, in _populate_page
    'page_markdown', page.markdown, page=page, config=config, files=files
  File "/Users/squidfunk/Desktop/General/Sources/mkdocs-material/venv/lib/python3.7/site-packages/mkdocs/plugins.py", line 94, in run_event
    result = method(item, **kwargs)
  File "/Users/squidfunk/Desktop/General/Sources/mkdocs-material/venv/lib/python3.7/site-packages/mkdocs_git_revision_date_localized_plugin/plugin.py", line 67, in on_page_markdown
    return Template(markdown).render({'git_revision_date_localized': revision_date})
  File "/Users/squidfunk/Desktop/General/Sources/mkdocs-material/venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/squidfunk/Desktop/General/Sources/mkdocs-material/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/squidfunk/Desktop/General/Sources/mkdocs-material/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/squidfunk/Desktop/General/Sources/mkdocs-material/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 137, in top-level template code
TypeError: no loader for this environment specified
```

After a clean install:

```
virtualenv venv
. venv/bin/activate
pip install -r requirements.txt
pip install mkdocs-git-revision-date-localized-plugin
mkdocs serve
```

**Comment by timvink** [comment]
@squidfunk I'm unable to reproduce locally. Classic 'works on my machine' 

However I noticed the error `no loader for this environment specified` is related to `Jinja`. I simplified the code to use regex instead of `Template().render()`. Should solve the issue.

New version is on pypi, can you 

```python
pip install --upgrade mkdocs-git-revision-date-localized-plugin
```

And try again?

**Comment by squidfunk** [comment]
Jep, it works now, thanks! The rendering is not ideal yet, especially if sources are linked with metadata:

<img width="713" alt="Bildschirmfoto 2019-12-11 um 17 20 06" src="https://user-images.githubusercontent.com/932156/70639282-8f88a780-1c3a-11ea-9ffd-7d021d7a089e.png">

I will provide a fix via CSS.
