### ISSUE TITLE
Plugin incompatible with Python 3.5

### ISSUE THREAD

**Issue by tcitworld** [timvink/mkdocs-git-revision-date-localized-plugin#3]
[This line](https://github.com/timvink/mkdocs-git-revision-date-localized-plugin/blob/master/mkdocs_git_revision_date_localized_plugin/plugin.py#L33) makes use of an f-string which is only available with Python 3.6.

Sadly I can't have a newer Python version in my CI for now.

```
$ mkdocs -V
mkdocs, version 1.0.4 from /usr/local/lib/python3.5/dist-packages/mkdocs (Python 3.5)
$ mkdocs build
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/mkdocs/__main__.py", line 162, in build_command
    site_dir=site_dir
  File "/usr/local/lib/python3.5/dist-packages/mkdocs/config/base.py", line 197, in load_config
    errors, warnings = cfg.validate()
  File "/usr/local/lib/python3.5/dist-packages/mkdocs/config/base.py", line 107, in validate
    run_failed, run_warnings = self._validate()
  File "/usr/local/lib/python3.5/dist-packages/mkdocs/config/base.py", line 62, in _validate
    self[key] = config_option.validate(value)
  File "/usr/local/lib/python3.5/dist-packages/mkdocs/config/config_options.py", line 132, in validate
    return self.run_validation(value)
  File "/usr/local/lib/python3.5/dist-packages/mkdocs/config/config_options.py", line 572, in run_validation
    plgins[item] = self.load_plugin(item, cfg)
  File "/usr/local/lib/python3.5/dist-packages/mkdocs/config/config_options.py", line 580, in load_plugin
    Plugin = self.installed_plugins[name].load()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/dist-packages/mkdocs_git_revision_date_localized_plugin/plugin.py", line 33
    print(f"WARNING - plugin locale setting '{plugin_locale}' will overwrite mkdocs locale '{mkdocs_locale}'")
                                                                                                            ^
SyntaxError: invalid syntax
```

**Comment by timvink** [comment]
Thanks @tcitworld, you're right I should have supported python 2.7. Will release a new version later today and let you know.

**Comment by tcitworld** [comment]
Many thanks !

**Comment by timvink** [comment]
Just published `v0.4`. Retry your CI, or `pip install --upgrade mkdocs-git-revision-date-localized-plugin`

If it works please close the issue :)

**Comment by tcitworld** [comment]
This issue seems to be fixed, unfortunately I now have the same as https://github.com/timvink/mkdocs-git-revision-date-localized-plugin/issues/2#issuecomment-566099789

**Comment by timvink** [comment]
The fix had a bug...should work now
